# tcp
CONNECT_IP_PORT: ['localhost', 55555]
LISTEN_IP_PORT: ['0.0.0.0', 55555]
NUM_CLIENTS: 8
EPOCHS_PER_ROUND: 1

# training
EPOCHS: 150
BATCH_SIZE: 64
LR_DECAY: 0.01

BASELINE:
    DOWNSAMPLE: 1
    LEARNING_RATE: 0.001
    LOOKBACK: 10

LSTM:
    LEARNING_RATE: 0.0005
    OUTER_LAYER_SIZE: 128
    HIDDEN_LAYER_SIZE: 16
    LAYER_AMOUNT: 1
FFT:
    LEARNING_RATE: 0.001
    OUTER_LAYER_SIZE: 128
    HIDDEN_LAYER_SIZE: 8
    LAYER_AMOUNT: 2

# data
WINDOW_SIZE: 100
WINDOW_STEP: 50
SPLIT: 1000
TRAIN_SPLIT: 0.7
VAL_SPLIT: 0.00

# evaluation
THRESHOLD_STD: 4
ROLLING_MIN: 3
LOGS_PATH: "test/"

# logs
EXPERIMENT_NAME: 'bearing_experiment-1'
LOAD_COLUMNS: [0, 1, 2, 3] # [0, 2, 4, 6] #
LOAD_COLUMNS_DICT:
    bearing_experiment-1: [0, 2, 4, 6]
    bearing_experiment-2: [0, 1, 2, 3]
    bearing_experiment-3: [0, 1, 2, 3]
TRAIN_COLUMNS: [0, 1, 2, 3]
NUM_FEATURES: 1


# experiment
CLIENT_0:
    bearing_experiment-1: [ 0 ]
    bearing_experiment-2: [ 0 ]
    bearing_experiment-3: [ 0 ]
CLIENT_1:
    bearing_experiment-1: [ 2 ]
    bearing_experiment-2: [ 1 ]
    bearing_experiment-3: [ 1 ]
CLIENT_2:
    bearing_experiment-1: [ 4 ]
    bearing_experiment-2: [ 2 ]
    bearing_experiment-3: [ 2 ]
CLIENT_3:
    bearing_experiment-1: [ 6 ]
    bearing_experiment-2: [ 3 ]
    bearing_experiment-3: [ 3 ]