---
- name: Delete instance
  gcp_compute_instance:
      name: "{{ item.hostname }}"
      state: absent
      machine_type: "{{ item.machine_type }}"
      project: "{{ gcp_project }}"
      zone: "{{ zone }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      disks:
        - auto_delete: yes
          boot: yes
          initialize_params:
            disk_size_gb: 20
            source_image: "projects/ubuntu-os-cloud/global/images/ubuntu-minimal-2004-focal-v20210429"
      network_interfaces:
        - network: "{{ network }}"
          access_configs:
            - name: "External NAT"
              nat_ip: "{{ address }}"
              type: "ONE_TO_ONE_NAT"
      scopes:
        - https://www.googleapis.com/auth/compute

- name: Delete an IP address
  gcp_compute_address:
      name: "{{ item.hostname }}-ip"
      region: "{{ region }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
        - https://www.googleapis.com/auth/compute
      state: absent