---
roles:
  - name: geerlingguy.docker
    version: 3.0.0
  - name: geerlingguy.pip
    version: 2.0.0

collections:
  - name: community.kubernetes
    version: 1.1.1
  - name: community.docker
    version: 1.6.0
  - name: google.cloud
    version: 1.0.2
