SERVER_IP_PORT: ('localhost', 55555)
BIND_IP_PORT: ('0.0.0.0', 55555)
CLIENT_NUM: 2

EPOCHS: 150
BATCH_SIZE: 16
THRESHOLD: 0.1
LEARNING_RATE: 0.0005
LR_DECAY: 0.995
LAYER_SIZES: [128, 32, 8]
LOSS_FN: mse
SPLIT: 100

CLIENT_1:
    DATASET_PATH: data/kbm_dataset/stabilus_100.csv
    DATASET_COLUMNS: [0, 1, 2, 3]
    MODEL_PATH: model/trainer1