# tcp
CONNECT_IP_PORT: ['localhost', 55555]
LISTEN_IP_PORT: ['0.0.0.0', 55555]
NUM_CLIENTS: 4

# training
EPOCHS: 10
BATCH_SIZE: 64
LR_DECAY: 0.01
LSTM:
    LEARNING_RATE: 0.001
    OUTER_LAYER_SIZE: 256
    HIDDEN_LAYER_SIZE: 8
    LAYER_AMOUNT: 1
FFT:
    LEARNING_RATE: 0.001
    OUTER_LAYER_SIZE: 128
    HIDDEN_LAYER_SIZE: 8
    LAYER_AMOUNT: 2

# data
SPLIT: 100
TRAIN_SPLIT: 0.7
VAL_SPLIT: 0.08
USE_OPTIMAL_THRESHOLD: False
THRESHOLD_DEVIATIONS: 7
THRESHOLD_CALCULATION_PERIOD: [0.0, 0.7]

# evaluation
THRESHOLD_LSTM: 0.5
THRESHOLD_FFT: 15
PLOT_YLIM_VIBRATION: 1
PLOT_YLIM_LOSSES: 1
PLOT_YLIM_SCORES_FACTOR: 10
PLOT_SPLITS: False

# logs
EXPERIMENT_NAME: 'bearing_experiment-2'
LOGS_PATH: 'logs/bearing_experiment-2'


# experiment
CLIENT_0:
    DATASET_PATH: data/bearing/experiment-2
    DATASET_COLUMNS: [0]
    MODEL_PATH: bearing_experiment-2/bearing-0
CLIENT_1:
    DATASET_PATH: data/bearing/experiment-2
    DATASET_COLUMNS: [1]
    MODEL_PATH: bearing_experiment-2/bearing-1
CLIENT_2:
    DATASET_PATH: data/bearing/experiment-2
    DATASET_COLUMNS: [2]
    MODEL_PATH: bearing_experiment-2/bearing-2
CLIENT_3:
    DATASET_PATH: data/bearing/experiment-2
    DATASET_COLUMNS: [3]
    MODEL_PATH: bearing_experiment-2/bearing-3