# training
EPOCHS: 10
BATCH_SIZE: 64
LEARNING_RATE: 0.001
# data
TRAIN_SPLIT: 0.7
VAL_SPLIT: 0.08
DOWNSAMPLE: 1
# experiment
DATASET_PATH: 'data/2nd_test'
EXPERIMENT_NAME: 'bearing_experiment-2'
DATASET_COLUMN: 0

