PYTHONUNBUFFERED: 1
SERVER_IP: localhost
SERVER_PORT: 55555
CLIENT_PORT: 65430
CLIENT_NUM: 2

EPOCHS: 30
BATCH_SIZE: 16
THRESHOLD: 0.1
SPLIT: 10
LEARNING_RATE: 0.0005
LR_DECAY: 0.995
LAYERS_EXPONENT: 6
DATASET_PATH: data/bearing_dataset/bearings_1_10.csv
DATASET_COLUMNS: 0,1

MODEL_PATH: results/trainer1
