FROM tensorflow/tensorflow:2.8.0

ENV PYTHONUNBUFFERED=1
ENV PATH_APP /app
WORKDIR $PATH_APP

# the config file to be imported can be changed here and through -e in Kubernetes
ENV CONFIG_FILE config.yaml

COPY .. .

RUN pip install --no-cache-dir -r configs/requirements.txt

CMD [ "python", "./worker_training.py" ]