FROM tensorflow/tensorflow:2.8.0

ENV PYTHONUNBUFFERED=1
ENV PATH_APP /app
WORKDIR $PATH_APP

# TODO: import environment variables into config?

COPY .. .

RUN pip install --no-cache-dir -r configs/requirements.txt

CMD [ "python", "./worker_training.py" ]