# tcp
CONNECT_IP_PORT: ['localhost', 55555]
LISTEN_IP_PORT: ['0.0.0.0', 55555]
CLIENT_NUM: 2
# training
EPOCHS: 100
BATCH_SIZE: 64
LEARNING_RATE: 0.001
LR_DECAY: 0.01
OUTER_LAYER_SIZE: 128
HIDDEN_LAYER_SIZE: 8
LAYER_AMOUNT: 2
LOSS_FN: mse
# data
SPLIT: 30
VAL_SPLIT: 0.1
TRAIN_SPLIT: 0.8
# evaluation
THRESHOLD_LSTM: 0.0011
THRESHOLD_FFT: 0.011
PLOT_YLIM_VIBRATION: 1
PLOT_YLIM_LOSSES: 0.01
PLOT_SPLITS: False

# experiment
CLIENT_1:
    DATASET_PATH: data/bearing/experiment-2
    DATASET_COLUMNS: [0]
    MODEL_PATH: model/bearing/experiment-2/bearing-0

CLIENT_2:
    DATASET_PATH: data/bearing/experiment-2
    DATASET_COLUMNS: [1]
    MODEL_PATH: model/bearing/experiment-2/bearing-1