# tcp
SERVER_IP_PORT: ('localhost', 55555)
BIND_IP_PORT: ('0.0.0.0', 55555)
CLIENT_NUM: 2
# training
EPOCHS: 100
BATCH_SIZE: 16
LEARNING_RATE: 0.001
LR_DECAY: 0.01
OUTER_LAYER_SIZE: 128
HIDDEN_LAYER_SIZE: 8
LAYER_AMOUNT: 2
LOSS_FN: mse
# data
SPLIT: 4096
VAL_SPLIT: 0.1
TRAIN_SPLIT: 0.8
# evaluation
THRESHOLD_LSTM: 10 #  0.0011
THRESHOLD_FFT: 10 # 0.011
PLOT_YLIM_VIBRATION: 1
PLOT_YLIM_LOSSES: 2
PLOT_SPLITS: False
# experiment
CLIENT_1:
    DATASET_PATH: data/bearing/experiment-2
    DATASET_COLUMNS: [0]
    MODEL_PATH: model/bearing/experiment-2/[0]