SERVER_IP_PORT: ('localhost', 55555)
BIND_IP_PORT: ('0.0.0.0', 55555)
CLIENT_NUM: 2

EPOCHS: 50
BATCH_SIZE: 16
LEARNING_RATE: 0.0001
LR_DECAY: 0.001
LOSS_FN: mse
VAL_SPLIT: 0.1
TRAIN_SPLIT: 0.3
LAYER_SIZES: [128, 32, 8]
SPLIT: 30
THRESHOLD_LSTM: 0.0011
THRESHOLD_FFT: 0.011
PLOT_YLIM: 0.2
PLOT_SPLITS: False

CLIENT_1:
    DATASET_PATH: data/bearing/experiment-2
    DATASET_COLUMNS: [0]
    MODEL_PATH: model/bearing/experiment-2/[0]